# Generated by Django 4.2.6 on 2023-10-23 22:31

from django.db import migrations

def tipo_identificacion_inserts(apps, schema_editor):
    with open('./sql/tipo_identificacion.sql', 'r',encoding='utf-8') as sql_file:
        sql_query = sql_file.read()
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql_query)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pais_deps_ciudades_20231023_1722'),
    ]

    operations = [
        migrations.RunPython(tipo_identificacion_inserts),
    ]
